### ISSUE TITLE
Contribute HackerRank / HackerEarth / Codechef / Leetcode code strictly C/C++

### ISSUE THREAD

**Issue by amanBhawsar** [amanBhawsar/Coding-Tree#1]
Kindly check the name convention followed for in each platform and follow the same. 
Do 5+ Questions and then raise PR.
Also, add link to questions in each file.

**Comment by shkaushal** [comment]
Can I contribute to this? Thanks!

**Comment by amanBhawsar** [comment]
Yes @shkaushal Raise PR after doing 5+ Questions.

**Comment by NavyaIyanampudi** [comment]
Can I contribute to this?

**Comment by NavyaIyanampudi** [comment]
Added solutions for almost 15-20 questions of codechef contest problems

**Comment by amanBhawsar** [comment]
@NavyaIyanampudi  added some comments on your PR.
